name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches: [main]  # or your default branch

permissions:
  contents: write  # required for pushing to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'  # or '7.x' depending on your project

    - name: Publish Blazor WebAssembly app
      run: dotnet publish -c Release -o release

    - name: Change base href in index.html
      run: sed -i 's|<base href="/" />|<base href="/<REPO_NAME>/"/>|' release/wwwroot/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./release/wwwroot
